# Generated by Django 4.2.2 on 2024-12-03 16:00

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Garden",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=400)),
            ],
        ),
        migrations.CreateModel(
            name="GardenInfo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "light_intensity",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                ("soil_moisture", models.DecimalField(decimal_places=2, max_digits=5)),
                ("humidity", models.DecimalField(decimal_places=2, max_digits=5)),
                ("co2_level", models.DecimalField(decimal_places=2, max_digits=5)),
                ("soil_pH", models.DecimalField(decimal_places=2, max_digits=5)),
                (
                    "garden",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="garden.garden"
                    ),
                ),
            ],
        ),
    ]
